/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ApiKhataosRouteImport } from './routes/api/khataos'
import { Route as AppCustomerIndexRouteImport } from './routes/app.customer.index'
import { Route as AppCustomerVoiceRouteImport } from './routes/app.customer.voice'
import { Route as AppCustomerTrustRouteImport } from './routes/app.customer.trust'
import { Route as AppCustomerRepaymentsRouteImport } from './routes/app.customer.repayments'
import { Route as AppCustomerCreditRouteImport } from './routes/app.customer.credit'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiKhataosRoute = ApiKhataosRouteImport.update({
  id: '/api/khataos',
  path: '/api/khataos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomerIndexRoute = AppCustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerVoiceRoute = AppCustomerVoiceRouteImport.update({
  id: '/customer/voice',
  path: '/customer/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerTrustRoute = AppCustomerTrustRouteImport.update({
  id: '/customer/trust',
  path: '/customer/trust',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerRepaymentsRoute = AppCustomerRepaymentsRouteImport.update({
  id: '/customer/repayments',
  path: '/customer/repayments',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerCreditRoute = AppCustomerCreditRouteImport.update({
  id: '/customer/credit',
  path: '/customer/credit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/khataos': typeof ApiKhataosRoute
  '/app/': typeof AppIndexRoute
  '/app/customer/credit': typeof AppCustomerCreditRoute
  '/app/customer/repayments': typeof AppCustomerRepaymentsRoute
  '/app/customer/trust': typeof AppCustomerTrustRoute
  '/app/customer/voice': typeof AppCustomerVoiceRoute
  '/app/customer/': typeof AppCustomerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/khataos': typeof ApiKhataosRoute
  '/app': typeof AppIndexRoute
  '/app/customer/credit': typeof AppCustomerCreditRoute
  '/app/customer/repayments': typeof AppCustomerRepaymentsRoute
  '/app/customer/trust': typeof AppCustomerTrustRoute
  '/app/customer/voice': typeof AppCustomerVoiceRoute
  '/app/customer': typeof AppCustomerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/khataos': typeof ApiKhataosRoute
  '/app/': typeof AppIndexRoute
  '/app/customer/credit': typeof AppCustomerCreditRoute
  '/app/customer/repayments': typeof AppCustomerRepaymentsRoute
  '/app/customer/trust': typeof AppCustomerTrustRoute
  '/app/customer/voice': typeof AppCustomerVoiceRoute
  '/app/customer/': typeof AppCustomerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/khataos'
    | '/app/'
    | '/app/customer/credit'
    | '/app/customer/repayments'
    | '/app/customer/trust'
    | '/app/customer/voice'
    | '/app/customer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/khataos'
    | '/app'
    | '/app/customer/credit'
    | '/app/customer/repayments'
    | '/app/customer/trust'
    | '/app/customer/voice'
    | '/app/customer'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/khataos'
    | '/app/'
    | '/app/customer/credit'
    | '/app/customer/repayments'
    | '/app/customer/trust'
    | '/app/customer/voice'
    | '/app/customer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiKhataosRoute: typeof ApiKhataosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/khataos': {
      id: '/api/khataos'
      path: '/api/khataos'
      fullPath: '/api/khataos'
      preLoaderRoute: typeof ApiKhataosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/customer/': {
      id: '/app/customer/'
      path: '/customer'
      fullPath: '/app/customer/'
      preLoaderRoute: typeof AppCustomerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer/voice': {
      id: '/app/customer/voice'
      path: '/customer/voice'
      fullPath: '/app/customer/voice'
      preLoaderRoute: typeof AppCustomerVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer/trust': {
      id: '/app/customer/trust'
      path: '/customer/trust'
      fullPath: '/app/customer/trust'
      preLoaderRoute: typeof AppCustomerTrustRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer/repayments': {
      id: '/app/customer/repayments'
      path: '/customer/repayments'
      fullPath: '/app/customer/repayments'
      preLoaderRoute: typeof AppCustomerRepaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer/credit': {
      id: '/app/customer/credit'
      path: '/customer/credit'
      fullPath: '/app/customer/credit'
      preLoaderRoute: typeof AppCustomerCreditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCustomerCreditRoute: typeof AppCustomerCreditRoute
  AppCustomerRepaymentsRoute: typeof AppCustomerRepaymentsRoute
  AppCustomerTrustRoute: typeof AppCustomerTrustRoute
  AppCustomerVoiceRoute: typeof AppCustomerVoiceRoute
  AppCustomerIndexRoute: typeof AppCustomerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCustomerCreditRoute: AppCustomerCreditRoute,
  AppCustomerRepaymentsRoute: AppCustomerRepaymentsRoute,
  AppCustomerTrustRoute: AppCustomerTrustRoute,
  AppCustomerVoiceRoute: AppCustomerVoiceRoute,
  AppCustomerIndexRoute: AppCustomerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiKhataosRoute: ApiKhataosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
